services:
  signed-api:
    container_name: signed-api
    image: ghcr.io/snow-platform/s3-signed-url:${VERSION}
    restart: unless-stopped
    environment:
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_ACCESS_KEY_SECRET=${R2_ACCESS_KEY_SECRET=}
      - R2_ENDPOINT=${R2_ENDPOINT}
    cpu_count: 1
    mem_limit: 512M
    mem_reservation: 256M
    networks:
      - proxy

networks:
  proxy:
    external: true
