name: release-create.yml

on:
  push:
    tags: 
      - 'v**'

jobs:
  tag:
    uses: snow-platform/workflows/.github/workflows/tag-check.yml@main
    secrets: inherit
  
  test:
    uses: snow-platform/workflows/.github/workflows/default-check-dotnet.yml@main
    with:
      version: '10.0.x'
      
  release:
    needs: [ tag, test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-tags: true
      - name: create release
        env:
          # This requires a PAT because a workflow that is triggered by release cannot run 
          # if the release is created by GITHUB_TOKEN
          GH_TOKEN: ${{ secrets.YUKI_TOKEN }}
          TAG: ${{ needs.tag.outputs.tag }}
        run: |
          gh release create $TAG --generate-notes --verify-tag
